fields:
  - "$.level"
  - "$.ts"
  - "$.msg"
jsonFields:
  - "$.attributes.request"
  - "$.attributes.response"
skips:
  - "request authenticated and authorized successfully"
  - "auth: skipping auth"
color: true